### ISSUE TITLE
Implementation of JAXB-API has not been found on module path or classpath

### ISSUE THREAD

**Issue by skilletti** [a-schild/nextcloud-java-api#79]
I am trying to call `getProperties()` method from `NextcloudConnector`. For some reason I receive this exception:

```
Caused by: java.lang.ExceptionInInitializerError
	at com.github.sardine.impl.SardineImpl.addCustomProperties(SardineImpl.java:450)
	at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:440)
	at nextcloud.api@12.0.2/org.aarboard.nextcloud.api.webdav.Files.getProperties(Files.java:271)
	at nextcloud.api@12.0.2/org.aarboard.nextcloud.api.NextcloudConnector.getProperties(NextcloudConnector.java:1034)
	at org.skilletti.xmowerconsole/org.skilletti.xmowerconsole.nextcloud.NextCloudUploader.uploadFile(NextCloudUploader.java:41)
	at org.skilletti.xmowerconsole/org.skilletti.xmowerconsole.main.resources.ResourcesController.clickedButtonAdd(ResourcesController.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 53 more
Caused by: java.lang.RuntimeException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at com.github.sardine.util.SardineUtil.<clinit>(SardineUtil.java:92)
	... 60 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:168)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:355)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:508)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:465)
	at com.github.sardine.util.SardineUtil.<clinit>(SardineUtil.java:88)
	... 60 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:165)
	... 64 more
```

I suppose there is an issue with outdated packages from < Java8. I am running Java 19.

Can you please advice me a solution for my issue?

**Comment by a-schild** [comment]
Googling for the error message returns a lot of results.

https://stackoverflow.com/questions/73487651/java-implementation-of-jaxb-api-has-not-been-found-on-module-path-or-classpath

Basically it has to do with the javax name space

**Comment by skilletti** [comment]
Thank you very much. I tried the same packages except updating the latest versions, which did not work.
